spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playground?enabledTLSProtocols=TLSv1.2&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    password: root
    username: root
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100000
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
